import type { Metadata } from "next";
import "./globals.css";
import Theme from "@/theme";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { connectMongoDB } from "@/config/mongodb";

export const metadata: Metadata = {
  title: "Shey Wrok App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectMongoDB();
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Theme>{children}</Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
